# Milkymist Platform Support
snd-soc-milkymist-objs := milkymist-pcm.o milkymist-ac97.o

obj-$(CONFIG_SND_MILKYMIST_SOC) += snd-soc-milkymist.o

# Milkymist Machine Support
snd-soc-mm1-objs := mm1.o
obj-$(CONFIG_SND_MILKYMIST_SOC_MM1) += snd-soc-mm1.o
