# Milkymist Platform Support
snd-soc-milkymist-objs := milkymist-pcm.o
snd-soc-milkymist-ac97-objs := milkymist-ac97.o

obj-$(CONFIG_SND_MILKYMIST_SOC) += snd-soc-milkymist.o
obj-$(CONFIG_SND_MILKYMIST_SOC_AC97) += snd-soc-milkymist-ac97.o

# Milkymist Machine Support
snd-soc-mm1-objs := mm1.o
obj-$(CONFIG_SND_MILKYMIST_SOC_MM1) += snd-soc-mm1.o
