#ifndef __ASM_OFFSETS_H__
#define __ASM_OFFSETS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by Kbuild
 *
 */

#define TASK_STATE 0 /* offsetof(struct task_struct, state)	# */
#define TASK_FLAGS 12 /* offsetof(struct task_struct, flags)	# */
#define TASK_PTRACE 16 /* offsetof(struct task_struct, ptrace)	# */
#define TASK_BLOCKED 516 /* offsetof(struct task_struct, blocked)	# */
#define TASK_THREAD 480 /* offsetof(struct task_struct, thread)	# */
#define TASK_THREAD_INFO 4 /* offsetof(struct task_struct, stack)	# */
#define TASK_MM 176 /* offsetof(struct task_struct, mm)	# */
#define TASK_ACTIVE_MM 180 /* offsetof(struct task_struct, active_mm)	# */
#define TASK_KSP 480 /* offsetof(struct task_struct, thread.ksp)	# */
#define TASK_USP 484 /* offsetof(struct task_struct, thread.usp)	# */
#define TASK_WHICH_STACK 488 /* offsetof(struct task_struct, thread.which_stack)	# */
#define STAT_IRQ 64 /* offsetof(struct kernel_stat, irqs)	# */
#define CPUSTAT_SOFTIRQ_PENDING 0 /* offsetof(irq_cpustat_t, __softirq_pending)	# */
#define THREAD_KSP 0 /* offsetof(struct thread_struct, ksp)	# */
#define THREAD_USP 4 /* offsetof(struct thread_struct, usp)	# */
#define THREAD_WHICH_STACK 8 /* offsetof(struct thread_struct, which_stack)	# */
#define PT_R0 0 /* offsetof(struct pt_regs, r0)	# */
#define PT_R1 4 /* offsetof(struct pt_regs, r1)	# */
#define PT_R2 8 /* offsetof(struct pt_regs, r2)	# */
#define PT_R3 12 /* offsetof(struct pt_regs, r3)	# */
#define PT_R4 16 /* offsetof(struct pt_regs, r4)	# */
#define PT_R5 20 /* offsetof(struct pt_regs, r5)	# */
#define PT_R6 24 /* offsetof(struct pt_regs, r6)	# */
#define PT_R7 28 /* offsetof(struct pt_regs, r7)	# */
#define PT_R8 32 /* offsetof(struct pt_regs, r8)	# */
#define PT_R9 36 /* offsetof(struct pt_regs, r9)	# */
#define PT_R10 40 /* offsetof(struct pt_regs, r10)	# */
#define PT_R11 44 /* offsetof(struct pt_regs, r11)	# */
#define PT_R12 48 /* offsetof(struct pt_regs, r12)	# */
#define PT_R13 52 /* offsetof(struct pt_regs, r13)	# */
#define PT_R14 56 /* offsetof(struct pt_regs, r14)	# */
#define PT_R15 60 /* offsetof(struct pt_regs, r15)	# */
#define PT_R16 64 /* offsetof(struct pt_regs, r16)	# */
#define PT_R17 68 /* offsetof(struct pt_regs, r17)	# */
#define PT_R18 72 /* offsetof(struct pt_regs, r18)	# */
#define PT_R19 76 /* offsetof(struct pt_regs, r19)	# */
#define PT_R20 80 /* offsetof(struct pt_regs, r20)	# */
#define PT_R21 84 /* offsetof(struct pt_regs, r21)	# */
#define PT_R22 88 /* offsetof(struct pt_regs, r22)	# */
#define PT_R23 92 /* offsetof(struct pt_regs, r23)	# */
#define PT_R24 96 /* offsetof(struct pt_regs, r24)	# */
#define PT_R25 100 /* offsetof(struct pt_regs, r25)	# */
#define PT_GP 104 /* offsetof(struct pt_regs, gp)	# */
#define PT_FP 108 /* offsetof(struct pt_regs, fp)	# */
#define PT_SP 112 /* offsetof(struct pt_regs, sp)	# */
#define PT_RA 116 /* offsetof(struct pt_regs, ra)	# */
#define PT_EA 120 /* offsetof(struct pt_regs, ea)	# */
#define PT_BA 124 /* offsetof(struct pt_regs, ba)	# */
#define STAT_IRQ 64 /* offsetof(struct kernel_stat, irqs)	# */
#define SIGSEGV 11 /* SIGSEGV	# */
#define SEGV_MAPERR 196609 /* SEGV_MAPERR	# */
#define SIGTRAP 5 /* SIGTRAP	# */
#define TRAP_TRACE 196610 /* TRAP_TRACE	# */
#define PT_PTRACED 1 /* PT_PTRACED	# */
#define PT_DTRACE 2 /* PT_DTRACE	# */
#define THREAD_SIZE 16384 /* THREAD_SIZE	# */
#define TI_TASK 0 /* offsetof(struct thread_info, task)	# */
#define TI_EXECDOMAIN 4 /* offsetof(struct thread_info, exec_domain)	# */
#define TI_FLAGS 8 /* offsetof(struct thread_info, flags)	# */
#define TI_CPU 12 /* offsetof(struct thread_info, cpu)	# */

#endif
